
import React from 'react';
import { X, Globe, DollarSign, Zap, Leaf, Microscope, Map as MapIcon, Dna, Swords, Users, Egg, Star, Wrench } from 'lucide-react';
import { COSTS, REFUND_RATE, XP_CONSTANTS, EGG_CONSTANTS, BODY_PART_WEIGHT } from '../constants';

interface RulesModalProps {
  onClose: () => void;
}

const Section: React.FC<{ title: string; icon: React.ReactNode; children: React.ReactNode }> = ({ title, icon, children }) => (
  <div className="mb-8">
    <h3 className="text-xl font-orbitron text-teal-400 mb-3 flex items-center gap-2 border-b border-slate-800 pb-2">
      {icon} {title}
    </h3>
    <div className="text-slate-300 text-sm leading-relaxed space-y-2">
      {children}
    </div>
  </div>
);

const RulesModal: React.FC<RulesModalProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-teal-500/30 w-full max-w-4xl max-h-[90vh] rounded-xl shadow-2xl flex flex-col relative overflow-hidden">
        
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-slate-950">
          <div>
            <h2 className="text-3xl font-orbitron text-white tracking-wider">Mission Briefing</h2>
            <p className="text-teal-500 font-mono text-xs uppercase">TerraChimera Operations Manual v2.0</p>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-red-900/30 text-slate-400 hover:text-red-400 rounded-full transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 scrollbar-hide">
          
          <Section title="Primary Objective" icon={<Globe />}>
            <p>
              You represent a mega-corporation on the newly discovered planet <strong>TerraChimera</strong>. 
              Your goal is to become the dominant power by expanding your territory, building a robust economy, 
              and bio-engineering the ultimate lifeforms.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-400">
              <li>Expand your borders across the hex map.</li>
              <li>Outpace rival corporations (GeoForge, BioGenesis, Aether Vanguard).</li>
              <li>Win tournaments to gain fame and fortune.</li>
            </ul>
          </Section>

          <Section title="The Economy" icon={<DollarSign />}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
              <div className="bg-slate-950 p-3 rounded border border-slate-800">
                <div className="flex items-center gap-2 text-yellow-500 font-bold mb-1"><DollarSign size={16}/> Credits</div>
                <p className="text-xs">Used for construction, hiring staff, and territory claims. Generated by <strong>Mining Rigs</strong> and base corporate funding. Be careful: Staff salaries reduce your Credit income per tick.</p>
              </div>
              <div className="bg-slate-950 p-3 rounded border border-slate-800">
                <div className="flex items-center gap-2 text-green-500 font-bold mb-1"><Leaf size={16}/> Biomass</div>
                <p className="text-xs">Raw organic material required to <strong>Incubate</strong> monsters and train them. Generated by <strong>Bio-Reactors</strong>.</p>
              </div>
              <div className="bg-slate-950 p-3 rounded border border-slate-800">
                <div className="flex items-center gap-2 text-blue-500 font-bold mb-1"><Zap size={16}/> Mana</div>
                <p className="text-xs">Exotic energy used for high-tier structures and magical enhancements. Harvested by <strong>Mana Pylons</strong>.</p>
              </div>
              <div className="bg-slate-950 p-3 rounded border border-slate-800">
                <div className="flex items-center gap-2 text-purple-500 font-bold mb-1"><Microscope size={16}/> Research</div>
                <p className="text-xs">Scientific data required to unlock advanced buildings. Generated by <strong>Scientists</strong> and <strong>Labs</strong>.</p>
              </div>
            </div>
          </Section>

          <Section title="Exploration & Territory" icon={<MapIcon />}>
            <p className="mb-2">The planet is covered in a "Fog of War". You can only see the biome and contents of sectors you have explored.</p>
            <ol className="list-decimal pl-5 space-y-2 text-slate-400">
              <li>
                <strong className="text-slate-200">Explore:</strong> Send an expedition to a dark hex adjacent to your territory. 
                <br/><em>Cost: {COSTS.EXPLORE_BASE} Credits (Reduced by Explorers).</em>
              </li>
              <li>
                <strong className="text-slate-200">Claim:</strong> Once explored, if a sector is neutral, you can Claim it to add it to your empire.
                <br/><em>Cost: {COSTS.CLAIM_BASE} Credits.</em>
              </li>
              <li>
                <strong className="text-slate-200">Build:</strong> You can only construct facilities on territory you own.
              </li>
              <li>
                <strong className="text-slate-200">Forage:</strong> Search explored territory for resources and potentially discover eggs!
                <br/><em>Egg Discovery Chance: {EGG_CONSTANTS.FORAGE_CHANCE * 100}%</em>
              </li>
              <li>
                <strong className="text-slate-200">Sabotage:</strong> You can pay to neutralize a rival's territory, destroying their building and resetting ownership.
              </li>
            </ol>
          </Section>

          <Section title="Bio-Synthesis (Monsters)" icon={<Dna />}>
            <p>
              In the <strong>Bio-Lab</strong>, you can spend Biomass to create new lifeforms. 
              Each creature belongs to an Element (Pyro, Hydro, Geo, Aero, Chrono, Bio) which determines its base stats and potential anatomy.
            </p>
            <p className="mt-2">
              <strong className="text-teal-400">Anatomy System:</strong> The AI generates a unique body chart for every monster. A creature might have wings, claws, tentacles, or cybernetic parts based on its element and traits.
            </p>
          </Section>

          <Section title="Eggs & Incubation" icon={<Egg />}>
            <p>
              Wild eggs can be discovered during <strong>Foraging</strong> or <strong>Exploration</strong>. Each egg has an element, quality rating, and incubation period.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-400">
              <li><strong className="text-white">Discovery:</strong> {EGG_CONSTANTS.FORAGE_CHANCE * 100}% chance when foraging.</li>
              <li><strong className="text-white">Incubation:</strong> Eggs require {EGG_CONSTANTS.MIN_INCUBATION_DAYS}-{EGG_CONSTANTS.MAX_INCUBATION_DAYS} days before hatching.</li>
              <li><strong className="text-white">Quality:</strong> Higher quality eggs (up to {EGG_CONSTANTS.MAX_QUALITY}%) produce stronger chimeras.</li>
              <li><strong className="text-white">Hatching Cost:</strong> {COSTS.INCUBATE_EGG} Biomass.</li>
            </ul>
          </Section>

          <Section title="XP & Progression" icon={<Star />}>
            <p>
              Chimeras gain <strong>XP (Experience Points)</strong> from tournament battles. XP can be spent on leveling up or enhancing specific stats.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-400">
              <li><strong className="text-white">Winning:</strong> +{XP_CONSTANTS.WIN_BASE} XP base (+{XP_CONSTANTS.LEVEL_BONUS} per opponent level)</li>
              <li><strong className="text-white">Losing:</strong> +{XP_CONSTANTS.LOSS_BASE} XP consolation</li>
              <li><strong className="text-white">Level Up:</strong> Costs {XP_CONSTANTS.XP_PER_LEVEL} × Current Level XP. Increases all stats and HP.</li>
              <li><strong className="text-white">Stat Enhancement:</strong> Spend {XP_CONSTANTS.ENHANCEMENT_COST} XP to boost a single stat by 3.</li>
            </ul>
          </Section>

          <Section title="Body Parts & Grafting" icon={<Wrench />}>
            <p>
              In the <strong>Grafting Lab</strong>, you can augment your chimeras with synthetic body parts. Each part has a material type, stat bonuses, and weight.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-400">
              <li><strong className="text-white">Categories:</strong> Offense, Defense, Mobility, Special</li>
              <li><strong className="text-white">Materials:</strong> Organic, Metallic, Crystalline, Ethereal, Composite (each has combat advantages against others)</li>
              <li><strong className="text-white">Weight System:</strong> Max Weight = Size × {BODY_PART_WEIGHT.MAX_WEIGHT_PER_SIZE}. Exceeding this reduces Speed by {BODY_PART_WEIGHT.SPEED_PENALTY_PER_EXCESS} per excess weight.</li>
              <li><strong className="text-white">Costs:</strong> Add ({COSTS.ADD_BODY_PART} Mana), Remove ({COSTS.REMOVE_BODY_PART} Mana), Enhance ({COSTS.ENHANCE_BODY_PART} Research)</li>
            </ul>
            <p className="mt-2 text-xs italic text-slate-500">
              Tip: Elemental body parts that match your chimera's element provide a +5% damage bonus per part!
            </p>
          </Section>

          <Section title="Staff & Management" icon={<Users />}>
            <p>
              Your HQ allows you to hire specialized personnel. Staff require a salary, which is deducted from your Credits every tick.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-400">
              <li><strong className="text-white">Explorers:</strong> Reduce the cost of exploring new hexes.</li>
              <li><strong className="text-white">Scientists:</strong> Generate passive Research points.</li>
              <li><strong className="text-white">Trainers:</strong> Reduce training costs for your chimeras.</li>
              <li><strong className="text-white">Beast Masters:</strong> Increase capture chance for wild monsters.</li>
            </ul>
            <p className="mt-2 text-xs italic text-slate-500">
              Tip: If your expenses exceed your income, you may need to Dismiss staff or Demolish buildings ({REFUND_RATE * 100}% refund) to stay afloat.
            </p>
          </Section>

          <Section title="Combat" icon={<Swords />}>
            <p>
              Some sectors contain <strong>Tournaments</strong>. Moving into these sectors allows you to enter the Arena. 
              Battles compare your monster's stats (Attack vs Defense, Speed modifiers) against an opponent.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-400">
              <li><strong className="text-white">Elemental Advantages:</strong> Elements are strong/weak against each other (1.5x damage)</li>
              <li><strong className="text-white">Material Effectiveness:</strong> Body part materials have advantages against other materials</li>
              <li><strong className="text-white">Body Part Synergy:</strong> Parts matching your element boost damage by 5% each</li>
              <li><strong className="text-white">Speed:</strong> Faster chimeras attack first; weight penalties reduce speed</li>
              <li><strong className="text-white">Rewards:</strong> Credits, XP, and potentially Trophies from tournament victories</li>
            </ul>
          </Section>

        </div>

        {/* Footer */}
        <div className="p-6 border-t border-slate-800 bg-slate-950 flex justify-end">
          <button 
            onClick={onClose}
            className="px-6 py-2 bg-teal-600 hover:bg-teal-500 text-white font-bold rounded transition-colors"
          >
            Acknowledge
          </button>
        </div>
      </div>
    </div>
  );
};

export default RulesModal;
